services:
  app:
    build: .
    tty: true
    volumes:
    - ./src/app:/usr/local/app
    working_dir: /usr/local/app
    environment:
      - PATH=/root/.cargo/bin:${PATH}
    command: ["tail", "-f", "/dev/null"]
